package com.example.core.designsystem.theme

import androidx.compose.ui.graphics.Color

//region Light
val primaryLight = Color(0xFF573568)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF8C669D)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF4C3E51)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF7F6F84)
val onSecondaryContainerLight = Color(0xFFFFFFFF)
val tertiaryLight = Color(0xFF623737)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF9A6767)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFF8C0009)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFDA342E)
val onErrorContainerLight = Color(0xFFFFFFFF)
val backgroundLight = Color(0xFFFFF7FC)
val onBackgroundLight = Color(0xFF1E1A1F)
val surfaceLight = Color(0xFFFFF7FC)
val onSurfaceLight = Color(0xFF1E1A1F)
val surfaceVariantLight = Color(0xFFEBDFEA)
val onSurfaceVariantLight = Color(0xFF484149)
val outlineLight = Color(0xFF645D65)
val outlineVariantLight = Color(0xFF817881)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF342F34)
val inverseOnSurfaceLight = Color(0xFFF8EEF6)
val inversePrimaryLight = Color(0xFFE3B7F4)
val surfaceDimLight = Color(0xFFE1D7DF)
val surfaceBrightLight = Color(0xFFFFF7FC)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFBF1F8)
val surfaceContainerLight = Color(0xFFF5EBF3)
val surfaceContainerHighLight = Color(0xFFEFE5ED)
val surfaceContainerHighestLight = Color(0xFFE9E0E7)
//endregion Light

//region Dark
val primaryDark = Color(0xFFE7BBF8)
val onPrimaryDark = Color(0xFF270538)
val primaryContainerDark = Color(0xFFAA82BB)
val onPrimaryContainerDark = Color(0xFF000000)
val secondaryDark = Color(0xFFD8C4DC)
val onSecondaryDark = Color(0xFF1D1222)
val secondaryContainerDark = Color(0xFF9C8BA1)
val onSecondaryContainerDark = Color(0xFF000000)
val tertiaryDark = Color(0xFFF9BBBA)
val onTertiaryDark = Color(0xFF2C0B0D)
val tertiaryContainerDark = Color(0xFFBA8382)
val onTertiaryContainerDark = Color(0xFF000000)
val errorDark = Color(0xFFFFBAB1)
val onErrorDark = Color(0xFF370001)
val errorContainerDark = Color(0xFFFF5449)
val onErrorContainerDark = Color(0xFF000000)
val backgroundDark = Color(0xFF161217)
val onBackgroundDark = Color(0xFFE9E0E7)
val surfaceDark = Color(0xFF161217)
val onSurfaceDark = Color(0xFFFFF9FB)
val surfaceVariantDark = Color(0xFF4C444D)
val onSurfaceVariantDark = Color(0xFFD2C7D2)
val outlineDark = Color(0xFFAAA0AA)
val outlineVariantDark = Color(0xFF89808A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE9E0E7)
val inverseOnSurfaceDark = Color(0xFF2D282E)
val inversePrimaryDark = Color(0xFF5D3A6D)
val surfaceDimDark = Color(0xFF161217)
val surfaceBrightDark = Color(0xFF3D373D)
val surfaceContainerLowestDark = Color(0xFF110D12)
val surfaceContainerLowDark = Color(0xFF1E1A1F)
val surfaceContainerDark = Color(0xFF231E23)
val surfaceContainerHighDark = Color(0xFF2D282E)
val surfaceContainerHighestDark = Color(0xFF383339)
//endregion Dark

//region Custom colors
val lightBlue500 = Color(0xFF06B1FB)
val purpleA700 = Color(0xFFBB06FB)
val amber600 = Color(0xFFFBB106)
val white = Color.White
//endregion Custom colors